# Generated by Django 3.1.4 on 2021-02-21 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210221_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
