# Generated by Django 3.1.4 on 2021-02-22 21:24

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210220_1422'),
        ('blog', '0004_auto_20210221_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=mptt.fields.TreeForeignKey(default='Random', on_delete=django.db.models.deletion.SET_DEFAULT, to='categories.category'),
        ),
    ]
