# Generated by Django 3.1.4 on 2021-02-24 14:20

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=django_bleach.models.BleachField(),
        ),
    ]
